### PR TITLE
Remove android compat and support dependencies

### PR DESCRIPTION
**Pull request by juank-pa**
I noticed that I use those two libraries to prevent complicating code in just a single spot. Instead of adding instructions for users on how to remove the unwanted libraries, or on how to recompile the ANE, or even instead of trying to remove the dependencies into external files as some other ANE developers do. I preferred solving the compat issues myself. This has many advantages:

* The is no dependencies to other libraries.
* The ANE is now a lot ligther than before (reduced from 1.5MB to 654KB).
* There is no need to solve collision issues with other ANEs.
* Simplifies usage.

**Note:** Only a coupe of files reflect the simplification. Others are small improvements to the test native Android app and specs.

### CODE REVIEW

**Comment by Sumeet-basak** [comment]
Will this work Oreo? last version did not.
Just asking. i will be testing it out anyways.

**Comment by juank-pa** [comment]
It tested it against Oreo emulator and it was working. If it is not working for you the only reason I can think of is that the AIR SDK you are using now supports Android SDK 26 and higher and that your app XML is set to use Android SDK 26 or higher as the target SDK. If these conditions met then notifications might not work. I'm really interested on making the ANE work on all versions. I haven't seen recent updates to the AIR SDK, so please confirm me if it is not working on Oreo and I handle it right away. Tell me which AIR SDK and target Android SDK versions you are using and I'll help you right away. This change will obviously force all users to download and start compiling against SDK 26 and thus I must think of a good upgrade strategy for them.

**Comment by juank-pa** [comment]
I was supporting AIR 26 I think and after researching we are now in AIR SDK 29. I'll take a further look too. AIR SDK 28 supports Android API 26 so it might not work if compiled with it, I'll handle this issue right away. Thanks

**Comment by juank-pa** [comment]
In the meantime please set Android SDK to 25 or lower in your application.xml file

**Comment by juank-pa** [comment]
UPDATE: After researching I noticed the following.

* AIR SDK 28 compiles using Android API level 25. So if you compiled your apk without overriding the sdk it should work on Oreo.
* AIR SDK 29 compiles using Android API level 27. Notifications might not work in this case but only if your app.xml file targets Android API level 26 or higher.
* No matter which AIR SDK or Android API level you use you'll have to downgrade to 25- as SDK target in the app.xml android manifest.

I though I could solve this issue easily but then I remembered why I never did it. 

Oreo and later changed the way notifications work. Oreo needs a notification channel to post notifications and this channel controls many properties such as sound, importance, visibility, etc of notifications posted in that channel that were previously set in a per-notification fashion. 

The current AS3 API sets all this properties for every notification (the way Android used to do before Oreo). If I update Android to use a "default" channel then all previously mentioned properties in the Notification will be ignored by the ANE because the "default" channel will set them.

To make the ANE support channels I'll need to move all these properties from the notification to the categories which could match Android channels, and that will introduced substantial breaking changes for all ANE users. Because I use semantic versioning I cannot introduce them in this version. My plan is to implement this in the near future as a mayor version upgrade but for now your best option is to target Android API level 25.

**Comment by juank-pa** [comment]
If you really need to target a greater API because of some other ANEs requirements please don't hesitate to tell me and maybe we can work on a feature branch together to get you a version suited to your needs, which could also serve as prototype for the next mayor version.

**Comment by Sumeet-basak** [comment]
Thank you Junak,


I am really struggling, with getting this down.

I will let you know where i stand tomorrow - i am currently debugging IAP not working because of conflicting SDKs


Thanks again.

Regards,

Sumeet.

________________________________

**Comment by Sumeet-basak** [comment]
i want to confirm that i am getting notifications on Oreo but or some reason it won't come when the application is killed. i have raised another issue regarding that, assuming that these two are not related.

**Pull request merged**
